javascripts:
    ga:
        - lib/ga.js
    lib:
        - lib/jquery-1.6.4.min.js
        - lib/jquery.Storage.js
        - lib/bootstrap-modal.js
        - lib/bootstrap-twipsy.js
        - lib/bootstrap-scrollspy.js
        - lib/bootstrap-popover.js
        - lib/underscore.js
        - lib/haml.js
        - lib/backbone-min.js
    template:
        - template/**/*.haml
    app:
        - tmp/javascript/model/**/*.js
        - tmp/javascript/view/**/*.js
        - tmp/javascript/main.js
        - tmp/javascript/route.js

stylesheets:
    common:
        - css/bootstrap.min.css
        - tmp/css/main.css

template_extension: haml
template_function: Haml
javascript_compressor: uglifier
compress_assets: off
gzip_assets: on